Description: |
  YAML Configuration file with all parameters
  This config file does not include any custom variables or any per product namespace variables.
  The file shows all global configuration file variables with their default values .
  Users can override these values as needed.  Global variables can be omitted from the file if the default is desired.
  Global variables specified in the configuration file can also be overridden if given as command line parameters.
  For more specific per product config variables please refer to the sample config associated with that product
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for variable names

# The list of M365 Product/SCuBA baselines ScubaGear will assess. Can use ['*'] to include all products.
ProductNames: ['*']

# This parameter is used to authenticate to the different commercial/government environments.
# See https://github.com/cisagov/ScubaGear/blob/main/docs/configuration/parameters.md#m365environment
# for list of acceptable values
M365Environment: commercial

# The following fields are used to document what organization this configuration file belongs to.
OrgName: Department of Example
OrgUnitName: Subdepartment of Example

LogIn: true
DisconnectOnExit: false

# The following fields are used to authenticate to the M365 environment using
# an App ID and Certificate Thumbprint.
AppID: 0123456789abcdef01234566789abcde
CertificateThumbprint: fedcba9876543210fedcba9876543210fedcba98

# The OutJsonFileName, OutCsvFileName, and OutActionPlanFileName fields are used to
# specify the names of the output files generated by ScubaGear.
# Recommended to leave these as the default values unless you have a specific reason to change them.
OutJsonFileName: ScubaResults
OutCsvFileName: ScubaResults
OutActionPlanFileName: ActionPlan

# The OutPath, OutFolderName, OutProviderFileName, OutRegoFileName, and OutReportName fields
# are used to specify the output directory and file names for the results of the SCuBA assessment.
# Recommended to leave these as the default values unless you have a specific reason to change them.
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports

# ======================
# EXCLUSIONS : AAD
# ======================
# This is for the Azure Active Directory product
Aad:
  # Legacy authentication SHALL be blocked.
  MS.AAD.1.1v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group 1
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Users detected as high risk SHALL be blocked.
  MS.AAD.2.1v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 4c7739c3-b512-44ca-b7a5-c7dd63b5bc8a # Example Group 2
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Sign-ins detected as high risk SHALL be blocked.
  MS.AAD.2.3v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group 1
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Phishing-resistant MFA SHALL be enforced for all users.
  MS.AAD.3.1v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group 1
        - cb075a02-09cf-4754-a673-90345120e03b # Example Group 3
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # If phishing-resistant MFA has not been enforced, an alternative MFA method SHALL be enforced for all users.
  MS.AAD.3.2v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Phishing-resistant MFA SHALL be required for highly privileged roles.
  MS.AAD.3.6v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Managed devices SHOULD be required for authentication.
  MS.AAD.3.7v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Managed Devices SHOULD be required to register MFA
  MS.AAD.3.8v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Deviceflow block SHALL be enforced for all users.
  MS.AAD.3.9v1: &OrgCapExclusions
    CapExclusions:
      Groups:
        - 1a0161f4-318c-4415-b2a0-862bde2c9cde # Example Group
      Users:
        - 9d9ac7b2-5aa6-4830-a17a-6557e52140b0 # Example User

  # Permanent active role assignments SHALL NOT be allowed for highly privileged roles.
  MS.AAD.7.4v1: &OrgRolesExclusions
    RoleExclusions:
      Users:
        - 2a8adc58-b7c5-4086-a5cc-244b8df40ce8
      Groups:
        - 4a471183-d934-4fb4-b1b3-d9525e0e1b45

# ======================
# EXCLUSIONS : DEFENDER
# ======================
# This is for the Defender product
Defender:
  MS.DEFENDER.1.4v1: &CommonSensitiveAccountFilter
    # Defines sensitive accounts filters used to select accounts to assign to
    # the Strict Preset Security Policy for Exchange Online Protections
    # Values for each key should match those shown in the 'Apply Exchange
    # Online Protection' section of the manage protection settings dialog.
    SensitiveAccounts:
      IncludedUsers:
        - johndoe@random.example.com
      IncludedGroups:
        - Dune
      IncludedDomains:
        - random.mail.example.com
      ExcludedUsers:
        -
      ExcludedGroups:
        -
      ExcludedDomains:
        -
  MS.DEFENDER.1.5v1:
    *CommonSensitiveAccountFilter
    # Defines sensitive accounts filters used to select accounts to assign to
    # the Strict Preset Security Policy for Defender for Office 365.
    # Values for each key should match those shown in the 'Apply Defender for
    # Office 365 protection' section of the manage protection settings dialog.
    # Note:  This example uses a YAML alias to re-use MS.DEFENDER.1.4v1 values
  MS.DEFENDER.2.1v1: &UserImpersonationProtection
    # Defines sensitive user accounts by display name and email address in
    # the Strict and Standard Preset Security Policies impersonation
    # protection section.
    # Each value should be a string in the form of the display name and
    # email address separated by a semicolon.
    SensitiveUsers:
      - John Doe;jdoe@someemail.com
  MS.DEFENDER.2.2v1: &AgencyDomainImpersonationProtection
    # Defines a list of agency domain names that should be specified
    # in the Strict and Standard Preset Security Policies impersonation
    # protection section.
    AgencyDomains:
      - random.mail.example.com
  MS.DEFENDER.2.3v1: &PartnerDomainImpersonationProtection
    # Defines a list of frequent partner domain names that should be
    # specified in the Strict and Standard Preset Security Policies
    # impersonation protection section.
    PartnerDomains:
      - random.mail.example.com

# ======================
# EXCLUSIONS : EXO
# ======================
# This is for the Exchange Online product
Exo:
  MS.EXO.1.1v2:
    AllowedForwardingDomains:
      - example1.com
      - example2.com

# The OmitPolicy field can be used to exclude policies from the SCuBA assessment
# results (e.g., for controls that are met using a third party tool).
# For in depth details, See https://github.com/cisagov/ScubaGear/blob/main/docs/configuration/configuration.md#omit-policies
# Note:  This section is used to omit policies from the assessment from any product.
#       The policies listed here will not be included in the assessment results.
#       You must provide a rationale for each omitted policy.
OmitPolicy:
